disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - line_length
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
